const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.ScriptsInEvents.Geral_Event18_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.ScriptsInEvents.Fase2_Event7_Act2,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{RestritoAoLayout: 0},
	{Pin: 0},
	{CentrarEm: 0},
	{mainAnimacao: 0},
	{Plataforma: 0},
	{MainColisao: 0},
	{Teclado: 0},
	{Sólido: 0},
	{colisaoObjeto: 0},
	{PlanoDeFundo: 0},
	{ArvoreBack: 0},
	{predioBack1: 0},
	{PredioBack2: 0},
	{Mosaico: 0},
	{Skate2: 0},
	{GradeBack: 0},
	{GradeFase: 0},
	{Grama1: 0},
	{Grama2: 0},
	{Banco: 0},
	{rocha1: 0},
	{rocahp: 0},
	{grama3: 0},
	{grama4: 0},
	{grama5: 0},
	{Direction: 0},
	{Piscar: 0},
	{Enemyskate: 0},
	{SensorEnemyDireita: 0},
	{SensorEnemyEsquerda: 0},
	{rampa1: 0},
	{Rampa2: 0},
	{skate1: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{playHistoria: 0},
	{logo: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{playGame: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{GameOverBackGround: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{playGame2: 0},
	{Menu: 0},
	{Áudio: 0},
	{Âncora: 0},
	{txtVidas: 0},
	{GradeBack2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{rampa3: 0},
	{arvoleBalanco: 0},
	{Caixa: 0},
	{caxinnha: 0},
	{graminhaCaxinha: 0},
	{grama14: 0},
	{grama11: 0},
	{grama12: 0},
	{rocha5: 0},
	{rocha6: 0},
	{banco2: 0},
	{fonte: 0},
	{Sprite: 0},
	{Sprite9: 0},
	{direcao: 0},
	{Sprite10: 0},
	{FonteDeSprites: 0},
	{FonteDeSprites2: 0},
	{boss: 0},
	{Mouse: 0},
	{história: 0},
	{cora: 0},
	{Vidas: 0},
	{VidaBoss: 0}
];

self.InstanceType = {
	mainAnimacao: class extends self.ISpriteInstance {},
	MainColisao: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	colisaoObjeto: class extends self.ISpriteInstance {},
	PlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	ArvoreBack: class extends self.ISpriteInstance {},
	predioBack1: class extends self.ISpriteInstance {},
	PredioBack2: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Skate2: class extends self.ISpriteInstance {},
	GradeBack: class extends self.ISpriteInstance {},
	GradeFase: class extends self.ISpriteInstance {},
	Grama1: class extends self.ISpriteInstance {},
	Grama2: class extends self.ISpriteInstance {},
	Banco: class extends self.ISpriteInstance {},
	rocha1: class extends self.ISpriteInstance {},
	rocahp: class extends self.ISpriteInstance {},
	grama3: class extends self.ISpriteInstance {},
	grama4: class extends self.ISpriteInstance {},
	grama5: class extends self.ISpriteInstance {},
	Enemyskate: class extends self.ISpriteInstance {},
	SensorEnemyDireita: class extends self.ISpriteInstance {},
	SensorEnemyEsquerda: class extends self.ISpriteInstance {},
	rampa1: class extends self.ISpriteInstance {},
	Rampa2: class extends self.ISpriteInstance {},
	skate1: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	playHistoria: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	playGame: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	GameOverBackGround: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	playGame2: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	txtVidas: class extends self.ISpriteFontInstance {},
	GradeBack2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	rampa3: class extends self.ISpriteInstance {},
	arvoleBalanco: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	caxinnha: class extends self.ISpriteInstance {},
	graminhaCaxinha: class extends self.ISpriteInstance {},
	grama14: class extends self.ISpriteInstance {},
	grama11: class extends self.ISpriteInstance {},
	grama12: class extends self.ISpriteInstance {},
	rocha5: class extends self.ISpriteInstance {},
	rocha6: class extends self.ISpriteInstance {},
	banco2: class extends self.ISpriteInstance {},
	fonte: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	boss: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	história: class extends self.ISpriteFontInstance {},
	cora: class extends self.ISpriteInstance {}
}